---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.42.10"}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[chef-doorman::default]
    attributes:
